// File generated by FlutterFire CLI.
// This is a placeholder - run: flutterfire configure
// to generate the actual configuration for your Firebase project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKM1K3g7mP6o8nkJjceFOVSNoYQg9Ln2o',
    appId: '1:467905378630:web:a1e84aece8a010efebcd47',
    messagingSenderId: '467905378630',
    projectId: 'amc-2025',
    authDomain: 'amc-2025.firebaseapp.com',
    storageBucket: 'amc-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKPkSRJeaxiJxeiF_bvUxJnIzcM6YJnvo',
    appId: '1:467905378630:android:cd10bb27c5ae84b6ebcd47',
    messagingSenderId: '467905378630',
    projectId: 'amc-2025',
    storageBucket: 'amc-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSJcC6TFF-W6wuZRIALxgpuPARVzvgHQ',
    appId: '1:467905378630:ios:45f0287979d35bddebcd47',
    messagingSenderId: '467905378630',
    projectId: 'amc-2025',
    storageBucket: 'amc-2025.firebasestorage.app',
    iosBundleId: 'com.example.amc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSJcC6TFF-W6wuZRIALxgpuPARVzvgHQ',
    appId: '1:467905378630:ios:45f0287979d35bddebcd47',
    messagingSenderId: '467905378630',
    projectId: 'amc-2025',
    storageBucket: 'amc-2025.firebasestorage.app',
    iosBundleId: 'com.example.amc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKM1K3g7mP6o8nkJjceFOVSNoYQg9Ln2o',
    appId: '1:467905378630:web:bde4fed0408bb3f4ebcd47',
    messagingSenderId: '467905378630',
    projectId: 'amc-2025',
    authDomain: 'amc-2025.firebaseapp.com',
    storageBucket: 'amc-2025.firebasestorage.app',
  );

}